pipeline {
    agent any
  
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Deliver') {
            steps {
                sh 'java -jar /var/jenkins/workspace/Java_Project_Pipeline/target/my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
