pipeline {
    agent any

    stages{
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t smilemukul/my-dockerapp:1.0 DevOps_Projects/java-maven-pipeline/.'
            }
        }
    }
}