pipeline {
    agent

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Local Docker Registry') {
            steps {
                sh 'docker run -d -p 5000:5000 --restart=always --name registry registry:2'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops_demo .'
            }
        }
        stage('Push Docker Image to Local Registery') {
            steps {
                sh 'docker tag devops_demo localhost:5000/my-devops-demo'
                sh  'docker push localhost:5000/my-devops-demo'
            }
        }
        stage('Remove locally-cached Docker Image') {
            steps {
                sh 'docker rmi devops_demo'
                sh 'docker rmi localhost:5000/my-devops-demo'
            }
        }
    }
}